version: "3"

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.web
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    links:
      - web
    ports:
      - "80:80"
    restart: always
  